# Generated by Django 4.2.6 on 2024-01-25 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('orders', '0004_alter_orderitem_cart_item_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drop_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.droppoint'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_arrival',
            field=models.DateField(blank=True, null=True),
        ),
    ]
