from django.core.management.base import BaseCommand
from user_profile.models import DropPoint, City, Region, Country


class Command(BaseCommand):
    help = "Populate DropPoint data to the database"

    def handle(self, *args, **options):
        drop_point_data = [
            {
                "name": "Kejetia Market",
                "city": "Kumasi",
                "region": "Ashanti Region",
                "country": "GH",
                "lon": "-1.610309",
                "lat": "6.688624",
                "info": "One of the largest markets in West Africa located in Kumasi.",
            },
            {
                "name": "Walewale Central Market",
                "city": "Walewale",
                "region": "North East Region",
                "country": "GH",
                "lon": "-0.556488",
                "lat": "8.557595",
                "info": "A bustling market in Walewale offering a variety of products.",
            },
            {
                "name": "Tamale Central Market",
                "city": "Tamale",
                "region": "Northern Region",
                "country": "GH",
                "lon": "-0.829591",
                "lat": "9.407406",
                "info": "A vibrant market in Tamale known for its diverse range of goods.",
            },
            {
                "name": "Kadjebi Bazaar",
                "city": "Kadjebi",
                "region": "Oti Region",
                "country": "GH",
                "lon": "0.003981",
                "lat": "7.213198",
                "info": "A local bazaar in Kadjebi offering various products.",
            },
            {
                "name": "Jasikan Shopping Center",
                "city": "Jasikan",
                "region": "Oti Region",
                "country": "GH",
                "lon": "0.673576",
                "lat": "7.983913",
                "info": "A popular shopping center in Jasikan.",
            },
            {
                "name": "Dambai Market Square",
                "city": "Dambai",
                "region": "Oti Region",
                "country": "GH",
                "lon": "0.912660",
                "lat": "7.384892",
                "info": "A vibrant market square in Dambai.",
            },
            {
                "name": "Sunyani Central Market",
                "city": "Sunyani",
                "region": "Bono Region",
                "country": "GH",
                "lon": "-2.327853",
                "lat": "7.331590",
                "info": "The central market in Sunyani.",
            },
            {
                "name": "Goaso Bazaar",
                "city": "Goaso",
                "region": "Ahafo Region",
                "country": "GH",
                "lon": "-2.292389",
                "lat": "7.050113",
                "info": "A bustling bazaar in Goaso.",
            },
            {
                "name": "Nkoranza Supermart",
                "city": "Nkoranza",
                "region": "Bono East Region",
                "country": "GH",
                "lon": "-1.948385",
                "lat": "7.156315",
                "info": "A well-known supermarket in Nkoranza.",
            },
            {
                "name": "Kintampo Electronics",
                "city": "Kintampo",
                "region": "Bono East Region",
                "country": "GH",
                "lon": "-1.722007",
                "lat": "8.056564",
                "info": "An electronics store in Kintampo known for quality gadgets and accessories.",
            },
            {
                "name": "Techiman Market Square",
                "city": "Techiman",
                "region": "Bono East Region",
                "country": "GH",
                "lon": "-1.944310",
                "lat": "7.585684",
                "info": "The market square in Techiman.",
            },
            {
                "name": "Yapei Bazaar",
                "city": "Yapei",
                "region": "Savannah Region",
                "country": "GH",
                "lon": "-0.995224",
                "lat": "9.817960",
                "info": "A local bazaar in Yapei.",
            },
            {
                "name": "Buipe Shopping Center",
                "city": "Buipe",
                "region": "Savannah Region",
                "country": "GH",
                "lon": "-1.635576",
                "lat": "8.083870",
                "info": "A shopping center in Buipe.",
            },
            {
                "name": "Damongo Mall",
                "city": "Damongo",
                "region": "Savannah Region",
                "country": "GH",
                "lon": "-1.953722",
                "lat": "8.567439",
                "info": "A mall in Damongo offering a mix of shops and entertainment.",
            },
            {
                "name": "Enchi Emporium",
                "city": "Enchi",
                "region": "Western North Region",
                "country": "GH",
                "lon": "-2.185954",
                "lat": "5.779310",
                "info": "A popular shopping destination in Enchi with a variety of shops.",
            },
            {
                "name": "Bibiani Plaza",
                "city": "Bibiani",
                "region": "Western North Region",
                "country": "GH",
                "lon": "-2.331350",
                "lat": "6.451743",
                "info": "A plaza in Bibiani featuring a range of shops and services.",
            },
            {
                "name": "Sefwi Wiawso Market",
                "city": "Sefwi Wiawso",
                "region": "Western North Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Sefwi Wiawso.",
            },
            {
                "name": "Ellembelle Market",
                "city": "Ellembelle",
                "region": "Western Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Ellembelle.",
            },
            {
                "name": "Tarkwa Market",
                "city": "Tarkwa",
                "region": "Western Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Tarkwa.",
            },
            {
                "name": "Sekondi-Takoradi Market",
                "city": "Sekondi-Takoradi",
                "region": "Western Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Sekondi-Takoradi.",
            },
            {
                "name": "Akatsi Market",
                "city": "Akatsi",
                "region": "Volta Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Akatsi.",
            },
            {
                "name": "Keta Market",
                "city": "Keta",
                "region": "Volta Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Keta.",
            },
            {
                "name": "Ho Market",
                "city": "Ho",
                "region": "Volta Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Ho.",
            },
            {
                "name": "Nandom Market",
                "city": "Nandom",
                "region": "Upper West Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Nandom.",
            },
            {
                "name": "Tumu Market",
                "city": "Tumu",
                "region": "Upper West Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Tumu.",
            },
            {
                "name": "Wa Market",
                "city": "Wa",
                "region": "Upper West Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Wa.",
            },
            {
                "name": "Navrongo Market",
                "city": "Navrongo",
                "region": "Upper East Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Navrongo.",
            },
            {
                "name": "Bawku Market",
                "city": "Bawku",
                "region": "Upper East Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Bawku.",
            },
            {
                "name": "Bolgatanga Market",
                "city": "Bolgatanga",
                "region": "Upper East Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Bolgatanga.",
            },
            {
                "name": "Dome Market",
                "city": "Dome",
                "region": "Greater Accra Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Dome.",
            },
            {
                "name": "Tema Market",
                "city": "Tema",
                "region": "Greater Accra Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Tema.",
            },
            {
                "name": "Accra Market",
                "city": "Accra",
                "region": "Greater Accra Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Accra.",
            },
            {
                "name": "Akim Oda Market",
                "city": "Akim Oda",
                "region": "Eastern Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Akim Oda.",
            },
            {
                "name": "Nsawam Market",
                "city": "Nsawam",
                "region": "Eastern Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Nsawam.",
            },
            {
                "name": "Koforidua Market",
                "city": "Koforidua",
                "region": "Eastern Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Koforidua.",
            },
            {
                "name": "Winneba Market",
                "city": "Winneba",
                "region": "Central Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Winneba.",
            },
            {
                "name": "Mankessim Market",
                "city": "Mankessim",
                "region": "Central Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Mankessim.",
            },
            {
                "name": "Cape Coast Market",
                "city": "Cape Coast",
                "region": "Central Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Cape Coast.",
            },
            {
                "name": "Berekum Market",
                "city": "Berekum",
                "region": "Brong-Ahafo Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Berekum.",
            },
            {
                "name": "Hwidiem Market",
                "city": "Hwidiem",
                "region": "Ahafo Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Hwidiem.",
            },
            {
                "name": "Yagaba-Kubori Market",
                "city": "Yagaba-Kubori",
                "region": "North East Region",
                "country": "GH",
                "lon": "N/A",
                "lat": "N/A",
                "info": "A market in Yagaba-Kubori.",
            },
        ]
        for entry in drop_point_data:
            # Get or create Country instance
            country, created = Country.objects.get_or_create(name=entry["country"])

            # Get or create Region instance
            region, created = Region.objects.get_or_create(
                name=entry["region"], country=country
            )

            # Get or create City instance
            city, created = City.objects.get_or_create(
                name=entry["city"], region=region
            )

            DropPoint.objects.create(
                name=entry["name"],
                city=city,
                region=region,
                country=country,
                lon=entry["lon"],
                lat=entry["lat"],
                info=entry["info"],
            )

        self.stdout.write(
            self.style.SUCCESS("DropPoint data successfully populated to the database.")
        )
